project:
  type: website
  output-dir: docs
  
website:
  title: "Jose Barajas Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/Josbae02
      - icon: github
        href: https://github.com/josebara002/personalwebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Jose Barajas"

format:
  html:
    theme: cerulean
    toc: true

editor: source

