project:
  type: website
  output-dir: docs
  
website:
  title: "Jose Barajas Personal Website"
  favicon: img/donuts.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/josebara/
      - icon: github
        href: https://github.com/josebara002/personalwebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Jose Barajas"

format:
  html:
    theme: zephyr
    toc: true

editor: source

